### ISSUE TITLE
大佬 问2个问题

### ISSUE THREAD

**Issue by yunv7** [zhaozhanzhan/jd_docker#2]
1、我设置好后运行docker-compose up -d 、docker-compose pull
我看拉取的都是zhaozhanzhan/jd_scripts而不是现在这个zhaozhanzhan/jd_docker这个库 需要改哪里改成拉现在的库吗？还是拉zhaozhanzhan/jd_scripts就对？
2、my_crontab_list.sh是不是非必须的，我看更新并不会更新这个文件，是不是不建立这个文件，就会用库里的docker/crontab_list.sh这个里的定时设置？

**Comment by zhaozhanzhan** [comment]
1.zhaozhanzhan/jd_scripts 这个是docke镜像库 ，https://hub.docker.com/在这里面可以搜到，可以相当于另一种形式的github，可以在上面发布自己的东西。你拉取的zhaozhanzhan/jd_scripts在启动成容器时会自动拉取zhaozhanzhan/jd_docker这个库进行更新

**Comment by yunv7** [comment]
了解了 多谢
