### ISSUE TITLE
大佬，能不能做个arm64的docker镜像

### ISSUE THREAD

**Issue by abcdsys** [zhaozhanzhan/jd_docker#3]
大佬，能不能做个arm64的docker镜像，谢谢

**Comment by zhaozhanzhan** [comment]
有了，可以试试

**Comment by abcdsys** [comment]
> 有了，可以试试

请问大佬，pull完镜像之后应该怎么运行呢？非群辉的docker
docker run zhaozhanzhan/jd_scripts?是这么运行吗？可以运行卡在 “启动crontab定时任务主进程...”
大佬有tg吗？

**Comment by zhaozhanzhan** [comment]
> > 有了，可以利用
> 
> 大佬，拉完镜像之后应该怎么运行呢？非
> 辉辉的docker docker run zhaozhanzhan/jd_scripts?是这么运行吗？运行卡在“启动crontab定时任务主进程...”
> 大佬有tg可以吗？

那就是成功了，TG需要有外网环境
